apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterCatalog
metadata:
  name: redhat-operators
  annotations:
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
  priority: -100
  source:
    type: image
    image:
      ref: registry.redhat.io/redhat/redhat-operator-index:v4.18
      pollInterval: 10m
  nodeSelector:
    node-role.kubernetes.io/master: ""
    kubernetes.io/os: "linux"
  priorityClassName: "system-cluster-critical"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Exists
      effect: NoSchedule
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: NoExecute
      tolerationSeconds: 120
    - key: "node.kubernetes.io/not-ready"
      operator: Exists
      effect: "NoExecute"
      tolerationSeconds: 120
  memoryTarget: 30Mi
  extractContent:
    cacheDir: /tmp/cache
    catalogDir: /configs
